apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: leaseforge-rolebinding
  namespace: leaseforge
subjects:
- kind: ServiceAccount
  name: leaseforge-sa
  namespace: leaseforge
roleRef:
  kind: Role
  name: leaseforge-role
  apiGroup: rbac.authorization.k8s.io
